### ISSUE TITLE
pytorch？

### ISSUE THREAD

**Issue by wukongbuku** [ShenhanQian/GaussianAvatars#32]
Why do you need to install cuda without writing pytorch and without specifying the version? 

Are you sure the requirements.txt is complete? There is no torch inside. . .

**Comment by ShenhanQian** [comment]
We use conda to install cuda-toolkit, which includes `nvcc` for compiling cuda extensions. This is different from installing PyTorch with CUDA runtime, which does not include `nvcc`.

We didn't specify the version of PyTorch because PyTorch has a good backward compatibility. Installing the latest one usually work well.

We didn't include cuda and pytorch in `requirements.txt` because we provide separate instructions for them to ensure compatibility.
