### ISSUE TITLE
How to render the canonical space images?

### ISSUE THREAD

**Issue by starcxl** [ShenhanQian/GaussianAvatars#40]
Hi, Shenhan, 

Many thanks for releasing your project, it's pretty awesome!

May I inquire how to render the canonical space Avatar's images? Like using the scripts to render novel expressions and poses: 
`python render.py -m output/UNION10EMOEXP_306_eval_600k --skip_train --skip_val  --render_mesh --select_camera_id 8`

Looking forward to your reply! Many thanks!

**Comment by ShenhanQian** [comment]
Hi, our method actually does not have a canonical space. Each Gaussian is defined in the local space of its parent triangle instead of in a shared canonical space.

If you need to render an image with a neutral pose and expression, you can set the corresponding parameters of FLAME to zeros in the code.

**Comment by starcxl** [comment]
I got it! Many thanks for your detailed reply! It works for me. Thanks again! ❤️

**Comment by starcxl** [comment]
I got it! Many thanks for your detailed reply! It works for me. Thanks again! ❤️
