### ISSUE TITLE
How to obtain FLAME mesh with hair?

### ISSUE THREAD

**Issue by ShaYito** [ShenhanQian/GaussianAvatars#5]
Thank you for your great work. I have one question. How to obtain FLAME mesh with hair? I checked the FLAME mesh model, and found out that it does not model hair. But in the pipeline and the data, I noticed that hair are part of the mesh. Could you tell me why? Thanks in advance.

**Comment by ShenhanQian** [comment]
As we explained in section A of our paper, we use a customized photometric tracker to fit FLAME to images. We are able to roughly model the hair with the vertex offset.

Meanwhile, GaussianAvatars can also run well without vertex offset on FLAME because the 3D Gaussians are allowed to shift from the mesh surface.

**Comment by nlml** [comment]
@hh0525  - for now the custom photometric tracker has not been released. I am not sure if Shenhan plans to release it.

**Comment by ShenhanQian** [comment]
We have released a head tracking repository: https://github.com/ShenhanQian/VHAP. 
It is not the same as the original tracker, but the output can be directly used by GaussianAvatars.
