### ISSUE TITLE
time 

### ISSUE THREAD

**Issue by Tiandishihua** [ShenhanQian/GaussianAvatars#8]
How long is the training time and the inference time?

**Comment by ShenhanQian** [comment]
We can get a decent avatar within several minutes. 

However, since the amount of data is very large, we use a long training schedule to conservatively add Gaussians and finetune FLAME parameters, which takes several hours to train a subject on a single GPU.

The inference (novel-view and novel-expression) on a subject takes about 10 minutes.

**Comment by ZYX-MLer** [comment]
> We can get a decent avatar within several minutes.
> 
> However, since the amount of data is very large, we use a long training schedule to conservatively add Gaussians and finetune FLAME parameters, which takes several hours to train a subject on a single GPU.
> 
> The inference (novel-view and novel-expression) on a subject takes about 10 minutes.

10 mintes / frame？
